export enum StorageKey {
  FORM_STATE = 'FORM_STATE',
}

export enum PluginMessageType {
  INIT = 'INIT',
  SET_INITIAL_STATE = 'SET_INITIAL_STATE',
  ON_CHANGE_FORM_STATE = 'ON_CHANGE_FORM_STATE',
  ON_CHANGE_SELECTION = 'ON_CHANGE_SELECTION',
  CHANGE_TEXT_NODE_CONTENT = 'CHANGE_TEXT_NODE_CONTENT',
}
