export enum SpellCheckReason {
  WRONG_SPELLING = 'WRONG_SPELLING',
  WRONG_SPACING = 'WRONG_SPACING',
  AMBIGUOUS = 'AMBIGUOUS',
  STATISTICAL_CORRECTION = 'STATISTICAL_CORRECTION',
}

export enum PluginMessageType {
  ON_CHANGE_SELECTION = 'ON_CHANGE_SELECTION',
  SPELL_CHECK_PAGE = 'SPELL_CHECK_PAGE',
  SPELL_CHECK_SELECTION = 'SPELL_CHECK_SELECTION',
}
