export enum SpellCheckReason {
  WRONG_SPELLING = 'WRONG_SPELLING',
  WRONG_SPACING = 'WRONG_SPACING',
  AMBIGUOUS = 'AMBIGUOUS',
  STATISTICAL_CORRECTION = 'STATISTICAL_CORRECTION',
}

export enum PluginMessageType {
  SET_CHARACTERS = 'SET_CHARACTERS',
  ON_CHANGE_CONTENT = 'ON_CHANGE_CONTENT',
}
